name: Scheduled Tests

on:
  schedule:
    - cron: '0 9 * * *'  # Runs at 09:00 UTC every day
    - cron: '0 17 * * *'  # Runs at 17:00 UTC every day

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest  # Change this to your test command
